version: "3.9"
services:
  test:
    build: .  # Build the image locally from Dockerfile
    image: "exercise-1"
    volumes:
      - .:/app
    command: python3 -m pytest

  run:
    build: .  # Build the image locally from Dockerfile
    image: "exercise-1"
    volumes:
      - .:/app
    command: python3 main.py
